### ISSUE TITLE
cant compile the .ino :(

### ISSUE THREAD

**Issue by guidol70** [phreda4/esp32-forth-computer#1]
I did try to compile the 2 .ino files, but do get an error while compiling :(
I have attached the errors as .txt file.
Do you got an idea what the problem could be?

I have made m_HVSyn public and commented it out in protected.

The view of code for the change in vgabasecontroller.h seems to depend on 
FabGL v1.0.3 - because there is only the line
`void setRawPixel(int x, int y, uint8_t rgb)    { VGA_PIXEL(x, y) = rgb; }`
in the file vgabasecontroller.h 
In v1.0.4/v1.0.5 this line doesnt exist anymore :(

I also used ESP32 Core v1.0.6 because the most FabGL code doesnt compile with v2.0.0/v2.0.1

[ino_compile_error.txt](https://github.com/phreda4/esp32-forth-computer/files/7675203/ino_compile_error.txt)

**Comment by guidol70** [comment]
from the error I did read that I have to move 
`  intr_handle_t          m_isr_handle;`
also from protected to public

Now the .ino does compile :)

But how do I get the /data directory with the .r3 files/library in the ESP32 SPIFFS Filesystem?

Iam using a TTGO VGA32 (which is FabGL compatible).
Should these files on the internal fash (as the sketch says SPIFFS ) or on the SDCard (on a TTGO VGA32)?

**[EDIT]** for the SPIFFS-File-Upload you have to install/use the
**ESP32 Filesystem Uploader** from [here](https://github.com/me-no-dev/arduino-esp32fs-plugin/releases/)

Copy the - in the .zip included - ESP32FS folder to your Arduino-Installtion in the folder tools :)

In the arduino-ide you will se the tool under Tools above the board-selection.

**Comment by phreda4** [comment]
I not try with new version of fabgl library, I try upload all the library for you can download all.
give me a couple of days
secod, you are correct, need to upload the file data

**Comment by phreda4** [comment]
I upload fabgl library in my system in 
https://drive.google.com/file/d/1YbkTJF_VDOPd4IJRx6sm8HzJuiflE_bg/view?usp=sharing

this file is the folder 
...\Documents\Arduino\libraries\FabGL
I remove docs and examples (80MB!!)
tellme if work !

**Comment by rpsubc8** [comment]
Congratulations on the project. I have tested it on a TTGO VGA32 v1.2 and v1.4, and it works perfectly.
You don't have to take into account what I am going to tell you, since it is your project. But you could make a simple modification that would not need to modify the fabgl library:

class VGADirectControllerPublic : public fabgl::VGADirectController
{
 public:
  intr_handle_t GetISRHandle() 
  {
   return m_isr_handle;
  }
  uint8_t GetHVSync()
  {
    return m_HVSync;
  }
};

VGADirectControllerPublic DisplayController;

Here I have left more information with the code:

http://retrowiki.es/viewtopic.php?f=86&t=200036016&start=320

**Comment by guidol70** [comment]
> I upload fabgl library in my system in 
> 
> this file is the folder ...\Documents\Arduino\libraries\FabGL
>  tellme if work !

I did work, but my Arduino IDE told me - after compiling - that you are using FabGL v1.0.2 and in your vgabasecontroller.h the 
  intr_handle_t          m_isr_handle;
is already in the public portion of the file.
In the Read.Me at your github-page this information is missing.

**Comment by phreda4** [comment]
Thank's a lot ackerman !!! 
I add to the github for other users, send me you nick or name for add to the credits

guido, try the ackerman modificatios, is more clear, I need this modification because
1. for speed, I generate pixels line by line.. not use the framebuffer..
2. the interrupt need for make SPIFF operation..LOAD, SAVE, DIR.. I need disable the generation on vga signal..

if any can traslate to other lib or make a version without lib, count with my help.. this code only use a fraction of fabgl lib

**Comment by guidol70** [comment]
> Thank's a lot ackerman !!! I add to the github for other users, send me you nick or name for add to the credits

This are the changes to the .ino which the compare-funtion of Notepad++ did found between the actual github-version and the version from ackerman:

![Modification_1](https://user-images.githubusercontent.com/5121124/145253258-e349a948-c2ba-4d22-a0f7-4ca529f9366c.jpg)

![Modification_2](https://user-images.githubusercontent.com/5121124/145253280-b37ac3fc-c87a-40a7-a001-be2a44c0707c.jpg)

Now I can check (think ackerman checked it alread) to put back the 2 lines to protected and recompile with v1.0.5 ;)
**[EDIT]** 
I successfully compiled it with an unchanged FabGL v1.0.5 (like ackerman).
When you have changed the .ino an the Read.Me we can strip the following line also from the .ino ;)

`// * Use FabGL Library with 2 changes (http://www.fabglib.org)`

**Comment by guidol70** [comment]
> Thank's a lot ackerman !!! I add to the github for other users, send me you nick or name for add to the credits

his nick should be:
https://github.com/rpsubc8 -> ackerman

**Comment by phreda4** [comment]
Thank's guido, if you have github I add you to access too

**Comment by rpsubc8** [comment]
Thank you very much, no need to include me in the credits. The important thing is to create a community of developers under ESP32, natively or emulation, and to be able to help each other.
In addition, of the esp32forthcomputer.ino, in the code I have also modified the r3.ino that is where the interrupts that phreda4 says are used:

void fastmode()
{
  //esp_intr_disable(DisplayController.m_isr_handle); 
  esp_intr_disable(DisplayController.GetISRHandle());  
}

void slowmode()
{ 
  //esp_intr_enable(DisplayController.m_isr_handle); 
  esp_intr_enable(DisplayController.GetISRHandle()); 
}

If the m_isr_handle and m_HVSync change depending on the fabgl version, we just have to modify the GetISRHandle and GetHVSync method of esp32forthcomputer.ino the return it returns.

I have tested with fabgl v1.0.5 and Arduino IDE 1.8.11 (espressif 1.0.4 and 1.0.6).

**Comment by guidol70** [comment]
> Thank's guido, if you have github I add you to access too

If you click here in the Message-Thread on my nick "guidol70" you will see, that Iam on Github as https://github.com/guidol70
;)

**Comment by guidol70** [comment]
> I have tested with fabgl v1.0.5 and Arduino IDE 1.8.11 (espressif 1.0.4 and 1.0.6).

I have tested with fabgl v1.0.5 and Arduino IDE 1.8.16 
(espressif ESP32 Core v1.0.6 ).
All fine :)

espressif ESP32 Core v2.0.0/v2.0.1 doesnt work with FabGL, so I have configured a portable 2nd installation with v1.0.6, because my main-installation uses v2.0.1 to support a ESP32-S2

**Comment by guidol70** [comment]
>  you are correct, need to upload the file data

here could you find a updated .jar for the ESP32 File Uploader plugin which also support the newer ESP32-Chipsets (like ESP32-S2):
https://github.com/lorol/arduino-esp32fs-plugin
